// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADCy27-wwlivaIJz3n9-N30sAkEJFb-v4',
    appId: '1:351118096288:android:6e0d71a11c9d6b49f2d6c5',
    messagingSenderId: '351118096288',
    projectId: 'foodigram-ed3ee',
    storageBucket: 'foodigram-ed3ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8OVIFy50FywKfLodso91KBkM9zxH8XQs',
    appId: '1:351118096288:ios:4ff683f49f9774ccf2d6c5',
    messagingSenderId: '351118096288',
    projectId: 'foodigram-ed3ee',
    storageBucket: 'foodigram-ed3ee.appspot.com',
    androidClientId: '351118096288-bct3mdmi48um2hnbfevk9l7dtmhgbofn.apps.googleusercontent.com',
    iosClientId: '351118096288-np3sufgj78s811q6cd32hr9ih3tr7tj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodigram',
  );
}
